apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database-backup.fullname" . }}-storage
  labels:
    {{- include "database-backup.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}